modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/Junk-Drawers/issues"
license="MIT"

[[mods]]
modId="junkdrawers"
version="${file.jarVersion}"
displayName="Junk Drawers"
displayURL="https://www.curseforge.com/minecraft/mc-mods/junk-drawers"
authors="Mrbysco, ShyNieke"
description='''
Let's just drop my inventory in here real quick
'''
[[dependencies.junkdrawers]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.junkdrawers]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.70-beta,)"
ordering="NONE"
side="BOTH"